apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-demo
  labels:
    app: lb-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lb-demo
  template:
    metadata:
      labels:
        app: lb-demo
    spec:
      containers:
      - name: lb-demo
        image: jsa5214/lb-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: lb-demo-svc
  annotations:
    # Esta anotación especifica que se cree un Network Load Balancer (NLB) de AWS
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: lb-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
